architecture in berlin   find documents on architecture in berlin
the electroweak theory   find documents that report recent discoveries in the field of subnuclear physics that confirm the unified electroweak theory of weinberg salam glashow
drugs in holland   what is the drugs policy in the netherlands  
floods in europe  find documents that give figures on the economic costs of the damage to agriculture caused by floods in europe
european union membership    identify attitudes of non member countries towardjoining the european community or european union
french conscientious objectors   what tasks are given to french conscientious objectors during their national service  
drug use and soccer   find documents about drug use in soccer
the suicide of pierre beregovoy   find documents on the suicide of former french prime minister pierre beregovoy
methane deposits    what locations throughout the world have methane gas deposits which can be converted to energy use  
war and radio   what role do radios play during war or armed conflict  
new constitution for south africa   find documents discussing the new constitution ofsouth africa and its final structure
solar temple   find documents on the order of the solar temple and the murder and orsuicide of its members
conference on birth control   what were the discussions and resolutions at the world population conference on birth control in cairo  
tourism in the u s what countries  other than canada  are sending large numbers of tourists to the u s   and what are the principal destinations of these tourists  
competitiveness of european industry   what are the factors that damage the competitiveness of european industry on the world s markets  
the french academy   find documents on the french academy
#q17=#sum(bush fire near sydney   what was the extent of the bush firesnear sydney and how dangerous was the situation  
#q18=#sum(firefighter casualties    find documents that discuss injuries to people engaged in firefighting
#q19=#sum(gulf war syndrome   find documents that discuss the gulf war syndrome
single european currency   what are the advantages and disadvantages of a single european currency  
european economic area   find documents about the european economic area  eea 
airplane runway accidents   identify instances where airplane accidentshave occurred on runways during flight operations
postmenopausal pregnancy   in 1994  a postmenopausal italian woman delivered a son  becoming the oldest woman in the world to give birth what was her name and how old was she  
world trade organization    what are the views in the u s in favor of gatt world trade organization  
corruption in italy                     which italian ex ministers have been imprisoned on the charge of accepting bribes                    
#q26=#sum(use of wind power    give examples of the use of wind power 
integration of german immigrants    why do german late immigrants find integrating difficult  
teaching techniques for non english speakers    what techniques are used in u s schools to teach students whose native language is otherthan english  
nobel prize for economics  who won the nobel prize for economics in 1994 and for what theory  
supermarket ceiling in nice collapses    what caused a supermarket in nice to cave in and what were the consequences  
#q31=#sum(consumer protection in the eu    find reports on consumer protection in the european union
female priests   find documents on the ordination of women in european churches
#q33=#sum(cancer genetics  find documents discussing recent discoveries on the relationship between genetics and cancer
alcohol consumption in europe   find documents on alcohol consumption in europe
wolves in italy   where can wolves be found in italy                       
olive oil production in the mediterranean   how much olive oil is produced in themediterranean area  
sinking of the estonia   find documents describing the sinking of the estonia ferry in the baltic sea and reporting ongoing investigations
#q38=#sum(return of military remains    identify instances of the remains of deceased military personnel being returnedto their home country for reburial
#q39=#sum(investments in eastern europe or russia    identify companies that are making orhave made investments in eastern europeor russia following the break up of theformer ussr
privatisation of german rail   find documents on the privatisation of the german railways
pesticides in baby food    find reports on pesticides in baby food
u n  us invasion of haiti    find documents on the invasion of haiti by u n  us soldiers
el nino and the weather    find reports explaining the  el nino  phenomenon and its repercussions on the world s weather  including effects on temperature  air pressure  rain fall  etc  
indurain wins tour    reactions to the fourth tour de france won by miguel indurain
israel jordan peace treaty    find reports citing the names of the main negotiators of the middle east peace treaty between israel and jordan and also documents giving detailed information on the treaty
embargo on iraq    what effects has the u n embargo had on the lives of the iraqi people   
russian intervention in chechnya    what are the reasons for the military intervention of  russia in chechnya   
peace keeping forces in bosnia    reasons for the withdrawal of united nations  un  peace  keeping forces from bosnia
fall in japanese car exports    documents will report on the decrease in cars exported by japan
revolt in chiapas    find reports on the uprising of indians in chiapas  mexico 
world soccer championship    find documents reporting on the final game of the world soccer championship of 1994
chinese currency devaluation    find documents describing the reasons and effects of the devaluation of chinese currency
genes and diseases    what genes have been identified that are the source of or contribute to the cause of diseases or developmental disorders in human beings   
final four results    find documents giving the results of the european basketball final four
swiss initiative for the alps     find documents that report on the swiss initiative aimed at regulating traffic through the alps
european campaigns against racism    find documents that talk about campaigns against racism in europe
tainted blood trial    find all information about the tainted blood trials in france including the sentences given by the court and the names of the people found guilty
euthanasia    documents will describe incidents of euthanasia understood as  death with dignity  or  the right to die 
computer viruses    find documents about computer viruses
corruption in french politics    find documents on corruption in politics in france  in particular with reference to the illegal financing of french political parties
siberian oil catastrophe    find information on the rupture of an oil pipeline in siberia
northern japan earthquake    find documents that report on an earthquake on the east coast of hokkaido  northern japan  in 1994
whale reserve    find documents about the reserve in the antarctic in which hunting for whales is forbidden
computer mouse rsi    find documents that report on computer mouse repetitive strain injuries  rsi 
treasure hunting    find documents about treasure hunters and treasure hunting activities
russian withdrawal from latvia    find reports and discussions about the withdrawal of russian troops from latvia
ship collisions    find information on the number of people injured or killed in collisions between ships
attacks on european synagogues    find documents that describe acts of terrorism or vandalism against european synagogues since the end of the second world war
cloning and ethics    what are the practical applications of cloning  and what are the ethical arguments against it   
death of kim il sung    find documents giving biographical information on kim il sung  the president of north korea  who died in 1994
vegetables  fruit and cancer    find documents that relate the eating of vegetables and fruit to cancer
g7 summit in naples    what role was played by russia in the g7 summit in naples in 1994   
norwegian referendum on eu    what were the reactions in the rest of europe to the negative results of the norwegian referendum in which norway decided against membership in the european union  eu 
inauguration of channel tunnel    find documents describing the inauguration of the channel tunnel and naming the national representatives of britain and france present at this ceremony
euskirchen court massacre    find documents on the court house massacre in euskirchen  germany  in which 7 people died
solar energy    in what applications is solar energy being used or being considered for future use   
teenage suicides    what information is available concerning teenage suicides   
venice film festival    which film or films won the golden lion in the 51st venice film festival in september 1994   
ulysses space probe    find documents that describe the european space probe mission ulysses or discuss its objectives
hunger strikes    documents will report any information relating to a hunger strike attempted in order to attract attention to a cause
french airbus hijacking    find all information concerning the role of an armed islamic group in the hijacking of an air france airbus
ira attacks in airports    find documents that describe terrorist acts by the irish republican army  ira  in european airports
auction of lennon memorabilia    find public auctions of john lennon memorabilia
shark attacks    documents will report any information relating to shark attacks on humans
turquoise program in rwanda    find detailed information on operation  turquoise   the french humanitarian program in rwanda
renewable power    find documents describing the use of or policies regarding  green  power  i e   power generated from renewable energy sources
inflation and brazilian elections    find documents analyzing the influence on the brazilian elections of the  plan real  against inflation
mad cow in europe    find documents that cite cases of bovine spongiform encephalopathy  the mad cow disease  in europe
schneider bankruptcy    find documents on the bankruptcy of the german property speculator jurgen schneider
vegetable exporters    what countries are exporters of fresh  dried or frozen vegetables   
ai in latin america    amnesty international reports on human rights in latin america
u n sanctions against iraq     what measures has iraq taken to effect the lifting of the u n economic embargo and political sanctions imposed after its invasion of kuwait in 1990   
eurofighter    find documents which report about the efa or the  eurofighter  project
return of solzhenitsyn    find documents which report about the return of the nobel prize winner for literature solzhenitsyn to russia
conflict in palestine    find articles dealing with armed conflicts in the palestinian territories and the involvement of a part of the civil population
should gonzalez resign     public requests by political personalities in spain for felippe gonzalez to resign  
referendum on the independence of moldova    find documents  that report about the referendum on the independence of the republic of moldova
films by the kaurismakis search for information about films directed by either of the two brothers aki and mika kaurismaki
denying the holocaust    find documents dealing with measures in germany to limit public actions denying the shoah
the ames espionage case    find documents that show the impact of the ames espionage case on u s  russian relations
cyprus and the eu    can cyprus become a member of the eu   
victories of alberto tomba    find documents that report on ski races won by alberto tomba
conflict of interests in italy    find documents that discuss the problem of the conflict of interests of the italian prime minister  silvio berlusconi
super g gold medal     who won the gold medal in the super g in lillehammer at the olympic winter games 1994   
bronchial asthma    find documents that talk about bronchial asthma and recent medical discoveries concerning this respiratory disease
european car industry    find documents which report about the situation in the european car industry regarding the fall in sales  sales crisis  and possible countermeasures
genetic engineering    how does genetic engineering effect the human food chain   
southern yemen secession    what are the social and economic consequences of the declaration of secession in southern yemen   
computer security     what is the status of computer security in regard to networked access   
iranian suspects extradited    france expelled to tehran two iranians suspected to have murdered kazem radjavi in switzerland
computer animation    find discussions of the impact of computer animation on the film industry
pulp fiction    what prize did the film pulp fiction by quentin tarantino win at the cannes film festival
european cup    find documents regarding the preliminary stages and other organisational issues regarding the 1996 european football cup
civil war in afghanistan    find all documents describing the political situation in afghanistan that led to civil war after the deposition of the communist leader najibullah
divorce statistics     provide statistics on divorce rates in different countries
the snowboard    find documents that discuss the introduction of a new winter sport  the snowboard
european parliament elections    how many voters were called to the polls to elect the new european parliament in 1994   
finland s first eu commissioner who was appointed as the first commissioner for finland in the european union   
destruction of ukrainian nuclear weapons    find documents which report about the agreement between the ukraine  russia and the usa on the removal and the destruction of ukrainian nuclear weapons before june 1996
edouard balladur    what is the importance for the european union of the economic policies of edouard balladur   
successes of ayrton senna    provide a record of the sporting achievements of brazilian race car driver ayrton senna
north american car industry    find documents discussing the efforts of the automobile industry in north america to improve their sales in both domestic and international markets
marriage jackson presley    find documents that report on the presumed marriage of michael jackson with lisa marie presley or on their separation
common foreign and security policy  cfsp     find information on establishing a common eu foreign and security policy
european single currency     what is the schedule predicted for the european single currency   
actions against the fur industry find information on protests or violent acts against the fur industry
escape of roldan     escape and flight of the spanish civil guard ex director luis roldan  
sex in advertisements    find articles dealing with eye catching  sexually oriented advertisements  and the consequences on  society
100 billion stars discovered    what technological breakthroughs permitted the discovery of an exceptionally high number of stars or galaxies in 1994
death of nirvana leader    how did the lead singer of the american rock and grunge group  nirvana  die   
intellectual property rights    find information on the rights of the developers of intellectual property and efforts by countries to provide protection for the developers
area of kaliningrad    find documents discussing the political or economic future of the kaliningrad exclave
german armed forces out of area    find documents which report on political and juridical decisions on out of area uses of the armed forces of germany
the clementine space probe    find reports on the american space probe clementine  launched to collect data about the moon and the near earth asteroid 1620 geographos
ec presidency candidates     who was mentioned as a possible candidate to be president of the european commission   
leaning tower of pisa    what is the state of health of the leaning tower of pisa   
international beauty contests    find the names of winners of international beauty contests in 1994 or 1995
foreign words in french    find documents dealing with the role of foreign words in french
eu fishing quotas    find information about fishing quotas in the eu
mobile phones    prospects for the use of cellular phones
letter bomb for kiesbauer    find information on the explosion of a letter bomb in the studio of the tv channel pro7 presenter arabella kiesbauer
christo wraps german reichstag    find reports on the wrapping of the german reichstag in berlin by the artist christo
women s conference beijing    controversial positions by a number of delegates meant that the women s conference in beijing risked failure
sierra leone rebellion and diamonds    what have been the effects of rebellions and other political instability on the sierra leone diamond industry   
japanese rice imports    find documents discussing reasons for and consequences of the first imported rice in japan
fast food in japan    what north american fast food chains have a large number of franchise restaurants in japan   
oil accidents and birds    find documents describing damage or injury to birds caused by accidental oil spills or pollution
damages in ozone layer    what holes in the ozone layer are not an effect of pollution   
pope s visit in sri lanka    find reports on protests or problems caused by previous declarations of the pope about buddhism during his visit to sri lanka
ai against death penalty    find reports on specific actions by amnesty international against the death penalty
wonders of ancient world    look for information on the existence and or the discovery of remains of the seven wonders of the ancient world
children s rights    find information on the united nations convention on the rights of the child
olympic games and peace    find documents which report on how the olympic games can contribute to world peace
free speech on the internet    find documents which discuss censorship and freedom of speech on the internet
risks with mobile phones    what risks and dangers are there with an increased use of mobile phones   
trade unions in europe    what are the differences in the role and importance of trade unions between european countries   
wimbledon lady winners    give the names of any winners of the wimbledon ladies tennis tournament
soccer riots in dublin    find reports on the suspension of the international soccer match between ireland and england in dublin after riots
north sea oil environment    what steps are being taken to protect the environment given the increase in oil exploration and production in the north sea   
scotch production consumption    documents will discuss the amount of scotch consumed by scots relative to the amount of scotch that is exported from scotland
diets for celiacs    find reports discussing diet problems of celiacs   
eu and turkish customs    find documents about the problems posed by greece concerning the abolishment of customs restrictions between the european union and turkey
smoking restrictions    find documents about regulations or laws that aim to prohibit or limit smoking in restaurants
european drug sentences    what sentences are given in europe for illegal dealing in drugs   
golden globes 1994    what movie won the golden globe for drama in the 1994 season   
french general and balkan security zone    who was the french general responsible for the creation of the security zone during the balkan conflict   
china mongolia relations    find information on recent relations and agreements for cooperation between china and mongolia
assassination of rabin    who shot yitzhak rabin and why   
advent of the cd burner    find documents about the cd burner and the reactions of the audio industry to it
official eu languages    find documents about french plans for reducing the number of official languages in the european union to five languages
lillehammer ice hockey finals    what teams played in the ice hockey finals at the 1994 olympic games in lillehammer   
1995 athletics world records    what new world records were achieved during the 1995 athletic world championships in gothenburg   
proof of top quarks    find reports on the experimental proof of top quarks by us researchers
bavarian crucifix quarrel    find reports on the crucifix quarrel in bavarian schools
everglades environmental damage    find reports on environmental damage in the everglades  for example caused by the florida sugar industry
shoemaker levy and jupiter    find reports on the break up of the shoemaker levy comet and its impact on the planet jupiter
milk consumption in europe    provide statistics or information concerning milk consumption in european countries
military service denial    find cases of people who are willing to risk imprisonment rather than perform military service
resignation of nato secretary general    why was the secretary general of nato forced to resign in 1995   
bankruptcy of barings    what was the extent of the losses in the barings bankruptcy case   
french nuclear tests    find reports of international pressure to put an end to french nuclear testing
50th anniversary of normandy landings    find reports on parachuting by veterans over sainte mere Eglise during the celebrations of the fiftieth anniversary of the normandy landings
asian dinosaur remains    in what parts of asia have dinosaur remains been found   
maternity leave in europe    find documents that give information on provisions concerning the length of maternity leave in europe
dutch photos of srebrenica    what happened to the photographs and films that dutch soldiers made in srebrenica which provided evidence of violations of human rights   
dutch coalition government    which political parties formed the ruling coalition  the so called purple cabinet  in the netherlands  in 1994 1995   
nuclear transport in germany    find reports on the protests against the transportation of radioactive waste with castor containers in germany
german spelling reform    find documents which report on the introduction of a spelling reform for the german language
hubble and black holes    what was the role of the hubble telescope in proving the existence of black holes   
child labor in asia    find documents that discuss child labor in asia and proposals to eliminate it or to improve working conditions for children
ebro delta farming    what was the predominant agricultural activity in the ebro delta in the early 1990s   
russian tv director murder    what was the name of the head of a russian tv company who was shot in the staircase of his home in moscow   
eu and baltic countries    find documents telling about the negotiations between baltic countries  estonia  latvia or lithuania  and the european union concerning eu membership
italian royal family    find information on the exile from italy of male members of the house of savoy
strikes by italian flight assistants    find reports on disruptions or problems caused by strikes by flight assistants in italy
merger of japanese banks    find reports on the merger of the japanese banks mitsubishi and bank of tokyo into the largest bank in the world
dayton peace treaty    find reports on the dayton agreement for the maintenance of peace in bosnia herzegovina
honorary oscar for italian directors    find information on italian film directors that have been awarded an honorary oscar for their lifetime work
ebola epidemic in zaire    find reports on preventive measures taken after the outbreak of the ebola epidemic in zaire
flooding in holland and germany    find statistics on flood disasters in holland and germany in 1995
